import { StyleSheet } from 'react-native'
export const Profile_Styles = StyleSheet.create({
    mainContainer: {
        backgroundColor: "white",
        flex: 1,
    },
    container: {
        backgroundColor: "lightblue",
        position: "absolute",
        marginTop: 150,
        width: "83%",
        height: 400,
        marginLeft: 70,
        borderTopLeftRadius: 160,
        borderBottomLeftRadius: 160,
    },
    main_text: {
        fontSize: 19,
        fontWeight: "bold",
        textShadowRadius: 4,
        marginLeft: 38,
        fontStyle: "italic",
        color: "black",
        marginTop: 63,
    },
    logout_maincontainer: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 40,
        borderRadius: 20,
        borderWidth: 2,
        marginLeft:70,
    },
    logout_text: {
        fontSize: 22,
        alignSelf: "center",
        fontWeight: "bold",
        marginTop: 15,
        color: "white",
    },
    my_account_text: {
        fontSize: 30,
        marginTop: 20,
        color: "black",
        alignSelf: "center",
        fontWeight: "bold",
        position:"absolute"
    },
    edit_text: {
        fontSize: 25,
        alignSelf: "center",
        fontWeight: "bold",
        marginTop: 10,
        marginLeft: 30,
        textDecorationLine: "underline",
        color: "black",
    },
    placeholder_text: {
        fontSize: 19,
        marginLeft: 36,
        color: "black",
        borderBottomWidth: 2,
        width: "60%",
        fontWeight: "bold",
    },
    formik_mainContainer: {
        backgroundColor: "lightblue",
        width: "94%",
        height: 450,
        marginTop: 180,
        borderRadius: 20,
        elevation: 60,
        marginLeft: 15,
    },
    error_text: {
        color: "red",
        fontSize: 15,
        marginLeft: 20,
    },
    submit_button: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 30,
        borderRadius: 20,
        borderWidth: 2,
    },
    submit_text: {
        fontSize: 22,
        alignSelf: "center",
        fontWeight: "bold",
        marginTop: 15,
        color: "white",
    },
    close: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 24,
        borderRadius: 20,
        borderWidth: 2,
    },
    text: {
        fontSize: 19,
        fontWeight: "bold",
        textShadowRadius: 4,
        marginLeft: 10,
        color: "black",
        marginTop: 20,
    },
    setting_icon: {
        color: "black",
        position: "absolute",
        alignSelf: "flex-end",
        padding: 8,
    },
    setting_modal: {
        width: 190,
        height: 80,
        backgroundColor: "lightblue",
        position: "absolute",
        top: 80,
        right: 5,
        borderRadius: 17,
    },
    setting_modal_text: {
        fontSize: 20,
        color: "black",
        fontWeight: "900",
        padding: 5,
        paddingLeft: 20
    }
})