import { StyleSheet } from 'react-native'
export const profile = StyleSheet.create({
    mainContainer: {
        backgroundColor: "white",
        flex: 1,
    },
    container: {
        backgroundColor: "lightblue",
        position: "absolute",
        marginTop: 150,
        width: "83%",
        height: 400,
        marginLeft: 70,
        borderTopLeftRadius: 160,
        borderBottomLeftRadius: 160,
    },
    mainText: {
        fontSize: 19,
        fontWeight: "bold",
        textShadowRadius: 4,
        marginLeft: 38,
        fontStyle: "italic",
        color: "black",
        marginTop: 63,
    },
    logoutMainContainer: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 40,
        borderRadius: 20,
        borderWidth: 2,
        marginLeft:70,
    },
    logoutText: {
        fontSize: 22,
        alignSelf: "center",
        fontWeight: "bold",
        marginTop: 15,
        color: "white",
    },
    myAccountText: {
        fontSize: 30,
        marginTop: 20,
        color: "black",
        alignSelf: "center",
        fontWeight: "bold",
        position:"absolute"
    },
    placeholderText: {
        fontSize: 19,
        marginLeft: 36,
        color: "black",
        borderBottomWidth: 2,
        width: "60%",
        fontWeight: "bold",
    },
    formikMainContainer: {
        backgroundColor: "lightblue",
        width: "94%",
        height: 450,
        marginTop: 180,
        borderRadius: 20,
        elevation: 60,
        marginLeft: 15,
    },
    errorText: {
        color: "red",
        fontSize: 15,
        marginLeft: 20,
    },
    submitButton: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 30,
        borderRadius: 20,
        borderWidth: 2,
    },
    submitText: {
        fontSize: 22,
        alignSelf: "center",
        fontWeight: "bold",
        marginTop: 15,
        color: "white",
    },
    close: {
        backgroundColor: "red",
        width: "50%",
        height: 60,
        alignSelf: "center",
        marginTop: 24,
        borderRadius: 20,
        borderWidth: 2,
    },
    text: {
        fontSize: 19,
        fontWeight: "bold",
        textShadowRadius: 4,
        marginLeft: 10,
        color: "black",
        marginTop: 20,
    },
    settingIcon: {
        color: "black",
        position: "absolute",
        alignSelf: "flex-end",
        padding: 8,
    },
    settingModal: {
        width: 190,
        height: 110,
        backgroundColor: "lightblue",
        position: "absolute",
        top: 80,
        right: 5,
        borderRadius: 17,
    },
    settingModalText: {
        fontSize: 20,
        color: "black",
        fontWeight: "900",
        padding: 5,
        paddingLeft: 20
    },
    musicNote:{
        left:20,
        color:"black",
    }
})